name: Node.js CI (24x7)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  keep-alive:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Repository එක checkout කරන්න
      uses: actions/checkout@v3

    - name: Node.js setup කරන්න
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Dependency install කරන්න
      run: npm ci

    - name: App එක Start කරන්න (background)
      run: |
        npm start &
        echo "App එක background එකේ run වෙලා ඉන්නේ..."

    - name: Keep alive 24 hours
      run: |
        echo "Job එක පැය 24 ක් idle වෙන්නේ නැතුව තියලා තියනවා..."
        sleep 86400  # 86400 seconds = 24 hours
