name: Node.js CI (24x7)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1440  # 24 hours

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install PM2 globally
      run: npm install pm2 -g

    - name: Start application with PM2
      run: |
        pm2 start npm --name "app" -- start
        pm2 save

    - name: Keep job alive
      run: |
        echo "App is running under PM2 with auto-restart enabled."
        for i in {1..1440}; do
          pm2 list  # Show PM2 process list every minute
          sleep 60
        done
